-- 1. FIND OUT COUNTRY NAME AND REGION NAME FROM COUNTRIES AND REGION TABLE
select country_name,region_name
from countries c
    inner join regions r on c.region_id=r.region_id;
    -- 2. FIND OUT FIRST_NAME AND JOB_TITLE FROM JOBS AND EMPLOYEES TABLE
select first_name,job_title
 from EMPLOYEES e
                inner join jobs j on j.JOB_ID = e.JOB_ID;

-- 3. FIND OUT DEPARTMENT_NAME AND CITY
select department_name, CITY
from DEPARTMENTS d
                inner join LOCATIONS l on d.LOCATION_ID=l.LOCATION_ID;

-- 4. FIND OUT ALL CITIES  AND COUNTRY NAMES
select city,COUNTRY_NAME
from LOCATIONS l
                inner join COUNTRIES c on l.COUNTRY_ID=c.COUNTRY_ID;

-- 5. FIND OUT FIRST_NAME, LAST NAME, DEPARTMENT ID , DEPARTMENT NAME  FOR DEPARTMENT ID 80 OR 40
select e.first_name,e.last_name,d.department_id,d.DEPARTMENT_NAME
from EMPLOYEES e
              inner join DEPARTMENTS d on e.DEPARTMENT_ID = d.DEPARTMENT_ID
              where d.DEPARTMENT_ID in (80,40);

-- 6. FIND OUT CITY , COUNTRY_NAME OF THAT CITY , REGION_NAME OF THAT CITY
select city,country_name,REGION_NAME
from LOCATIONS l
              inner join COUNTRIES c on l.COUNTRY_ID=c.COUNTRY_ID
              inner join REGIONS r on c.REGION_ID=r.REGION_ID;


-- 7. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY
select first_name,JOB_TITLE,DEPARTMENT_NAME,CITY
from EMPLOYEES e
              inner join jobs j on e.JOB_ID=j.JOB_ID
              inner join DEPARTMENTS d on e.DEPARTMENT_ID=d.DEPARTMENT_ID
              inner join LOCATIONS l on d.LOCATION_ID=l.LOCATION_ID;

-- 8. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY , COUNTRY_NAME , REGION_NAME
select e.FIRST_NAME,j.JOB_TITLE,d.DEPARTMENT_NAME,l.CITY,c.COUNTRY_NAME,r.REGION_NAME
from EMPLOYEES e
         inner join jobs j on e.JOB_ID=j.JOB_ID
         inner join DEPARTMENTS d on e.DEPARTMENT_ID=d.DEPARTMENT_ID
         inner join LOCATIONS l on d.LOCATION_ID=l.LOCATION_ID
         inner join COUNTRIES c on l.COUNTRY_ID=c.COUNTRY_ID
         inner join REGIONS r on c.REGION_ID=r.REGION_ID;


--9. FIND OUR  EMPLOYEES FIRST_NAME, LAST NAME, DEPARTMENT ID AND ALL DEPARTMENTS
--  INCLUDING  WHERE DO NOT HAVE ANY EMPLOYEE.
select e.first_name,e.LAST_NAME,d.DEPARTMENT_ID
from DEPARTMENTS d
                 left outer join EMPLOYEES e on d.DEPARTMENT_ID=e.DEPARTMENT_ID;

select e.first_name,e.LAST_NAME,d.DEPARTMENT_ID
from EMPLOYEES e
         right outer join DEPARTMENTS d  on d.DEPARTMENT_ID=e.DEPARTMENT_ID;

--10. FIND OUT ALL DEPARTMENT_NAME  , LOCATION_ID , AND COUNTRY_ID
-- INCLUDING THOSE LOCATIONS  WITH NO DEPARTMENT

--11.FIND OUT DEPARTMENT_NAME , LOCATION_ID , AND COUNTRY_NAME
-- INCLUDING THOSE COUNTRIES WITH NO DEPARTMENT

--12. FIND OUT EMPLOYEES FIRST_NAME, DEPARTMENT ID AND DEPARTMENT NAME
-- INCLUDING THOSE DOES NOT HAVE DEPARTMENT
-- INCLUDING THOSE DEPARTMENTS  DOES NOT HAVE ANY MATCHING EMPLOYEES
select FIRST_NAME,DEPARTMENT_NAME,d.DEPARTMENT_ID
from  EMPLOYEES e
                full outer join DEPARTMENTS d on e.DEPARTMENT_ID=d.DEPARTMENT_ID;